Repository splunk-soar-connectors/taniumrest, pull requests merged in 2021-12, with the labels that each got.

#2 TaniumREST: PAPP-20442: Bug fixes
  readme.html
  readme.md
  release_notes/unreleased.md
  taniumrest.json
  taniumrest_connector.py
  taniumrest_consts.py
  taniumrest_run_query.html
Labels: splunk-supported, PAPP-20442

#4 Tanium REST: Feature Request - PAPP-21244 added token authentication
  .pre-commit-config.yaml
  readme.html
  readme.md
  taniumrest.json
  taniumrest_connector.py
  taniumrest_run_query.html
Labels: documentation, splunk-supported

#6 Adding release notes for the token based authentication
  release_notes/unreleased.md
Labels: splunk-supported

#8 TaniumRest: resolve next to main conflict
  readme.md
  release_notes/2.1.4.md
  release_notes/release_notes.html
Labels: splunk-supported
